import add from "./add.svg"
import desc from "./desc.svg"
import trashBlack from "./trash-black.svg"
import facebook from "./facebook.svg"
import instagram from "./intagram.svg"
import linkedin from "./linkedin.svg"
import twitter from "./twitter.svg"
import surf from "./surf.png"
import userLogin from "./user-login.svg"
import trolley from "./trolley.svg"
import menu from "./menu.svg"

export { add }
export { desc }
export { trashBlack }
export { facebook }
export { instagram }
export { linkedin }
export { twitter }
export { surf }
export { userLogin }
export { trolley }
export { menu }
